In [1]:
import numpy as np
import pandas as pd 
from sklearn.datasets import load_breast_cancer

import warnings 
warnings.filterwarnings('ignore')

In [2]:
data = load_breast_cancer()

In [3]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
data.DESCR.split('\n')

['.. _breast_cancer_dataset:',
 '',
 'Breast cancer wisconsin (diagnostic) dataset',
 '--------------------------------------------',
 '',
 '**Data Set Characteristics:**',
 '',
 ':Number of Instances: 569',
 '',
 ':Number of Attributes: 30 numeric, predictive attributes and the class',
 '',
 ':Attribute Information:',
 '    - radius (mean of distances from center to points on the perimeter)',
 '    - texture (standard deviation of gray-scale values)',
 '    - perimeter',
 '    - area',
 '    - smoothness (local variation in radius lengths)',
 '    - compactness (perimeter^2 / area - 1.0)',
 '    - concavity (severity of concave portions of the contour)',
 '    - concave points (number of concave portions of the contour)',
 '    - symmetry',
 '    - fractal dimension ("coastline approximation" - 1)',
 '',
 '    The mean, standard error, and "worst" or largest (mean of the three',
 '    worst/largest values) of these features were computed for each image,',
 '    resulting in 30 feature

In [6]:
df = pd.DataFrame(data = data['data'], columns = data.feature_names)
df['target'] = data['target']
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [8]:
df['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [9]:
X = df.iloc[:, :-1]
y = df['target']


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state=42)

# Perceptron

In [11]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [17]:
def heaviside(X):
    return X>= .5

In [18]:
X.shape

(569, 30)

In [19]:
def update_weights(Weights, X, y_pred, y, lr):
    m = len(y)
    dw = (1/m)*(np.dot(X.T, y_pred-y))
    Weights = Weights - lr*dw
    return Weights
    

In [20]:
def update_bais(bais, y_pred, y, lr):
    m = len(y)
    db = (1/m)*(np.sum(y_pred-y))
    bais = bais - lr*db
    return bais

In [21]:
def perceptron(X, weights, bais):
    linear_prediction = np.dot(X, weights)+bais
    y_p = heaviside(linear_prediction)
    return y_p

In [22]:
def accuracy(y_pred, y_actual):
    return np.sum(y_pred==y_actual)/len(y_actual)

# Train

In [23]:
lr = 0.001
weights = np.zeros(X_train.shape[1])
bais =0

for i in range(1000):
    pred = perceptron(X_train, weights, bais)
    weights = update_weights(weights, X_train, pred, y_train, lr)
    bais = update_bais(bais, pred, y_train, lr)

In [24]:
weights

array([ 3.19349275e-01,  4.14405275e-01,  1.85353642e+00,  7.45238022e-01,
        2.86554862e-03, -1.50952046e-03, -5.88998813e-03, -2.51301631e-03,
        5.40101934e-03,  2.31377952e-03,  1.19822989e-03,  3.01258226e-02,
       -8.44353341e-03, -8.10596035e-01,  1.49466220e-04, -3.52314673e-04,
       -6.75947799e-04, -8.72441495e-05,  4.82322420e-04,  4.79238552e-05,
        3.36171637e-01,  5.15630066e-01,  1.87290855e+00, -1.08176242e+00,
        3.49712233e-03, -6.54406721e-03, -1.27012476e-02, -2.95060928e-03,
        6.92923231e-03,  2.10499633e-03])

In [25]:
bais

0.041789010989011034

In [26]:
y_test_pred = perceptron(X_test, weights, bais)
print('Accuracy : ', accuracy(y_pred, y_test))

Accuracy :  0.9473684210526315


In [28]:
y_train_pred = perceptron(X_train, weights, bais)
print('Accuracy : ', accuracy(y_train_pred, y_train))

Accuracy :  0.8835164835164835


In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(2, input_dim =30), 
    Dense(6),
    Dense(1, activation = 'sigmoid')
])

In [31]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 62        
                                                                 
 dense_3 (Dense)             (None, 6)                 18        
                                                                 
 dense_4 (Dense)             (None, 1)                 7         
                                                                 
Total params: 87 (348.00 Byte)
Trainable params: 87 (348.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [32]:
model.compile(loss = 'binary_crossentropy')

In [33]:
model.fit(X_train, y_train, epochs=100 )

Epoch 1/100

15/15 [==============================] - 2s 7ms/step - loss: 140.2648
Epoch 2/100
15/15 [==============================] - 0s 6ms/step - loss: 109.4748
Epoch 3/100
15/15 [==============================] - 0s 5ms/step - loss: 86.5989
Epoch 4/100
15/15 [==============================] - 0s 6ms/step - loss: 66.8695
Epoch 5/100
15/15 [==============================] - 0s 6ms/step - loss: 49.9030
Epoch 6/100
15/15 [==============================] - 0s 6ms/step - loss: 34.6690
Epoch 7/100
15/15 [==============================] - 0s 6ms/step - loss: 22.2137
Epoch 8/100
15/15 [==============================] - 0s 6ms/step - loss: 11.8262
Epoch 9/100
15/15 [==============================] - 0s 7ms/step - loss: 4.5455
Epoch 10/100
15/15 [==============================] - 0s 7ms/step - loss: 2.6593
Epoch 11/100
15/15 [==============================] - 0s 6ms/step - loss: 1.9903
Epoch 12/100
15/15 [==============================] - 0s 6ms/step - loss: 1.3251
Epoch 13/100
15/15 [======

15/15 [==============================] - 0s 3ms/step - loss: 0.2244
Epoch 100/100
15/15 [==============================] - 0s 3ms/step - loss: 0.2219


In [34]:
y_pred = model.predict(X_train)

15/15 [==============================] - 0s 3ms/step


In [35]:
y_pred[:10]

array([[9.6475613e-01],
       [1.2005657e-07],
       [9.7593355e-01],
       [9.7270364e-01],
       [9.7044832e-01],
       [2.1329781e-01],
       [7.6063180e-01],
       [9.7854877e-01],
       [9.4662488e-01],
       [4.4130927e-04]], dtype=float32)

In [36]:
y_pred = y_pred>.5

In [37]:
y_pred[:10]

array([[ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False]])

In [43]:
print(f'Accuracy : {accuracy(y_train.values.reshape(y_pred.shape), y_pred)*100 :.2f}%')

Accuracy : 91.21%
