In [1]:
import numpy as np

###  Write a NumPy program to test whether none of the elements of a given array is zero.

In [3]:
def none_zero(arr):
    return not np.any(arr == 0)
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 0, 4])
print("Array 1:", arr1)
print("None of the elements in array 1 are zero:", none_zero(arr1))

print("Array 2:", arr2)
print("None of the elements in array 2 are zero:", none_zero(arr2))

Array 1: [1 2 3 4]
None of the elements in array 1 are zero: True
Array 2: [1 2 0 4]
None of the elements in array 2 are zero: False


####  Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [5]:
def none_zero(arr):
    return  np.any(arr == 0)
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 0, 4])
print("Array 1:", arr1)
print("any of the elements in array 1 are zero:", none_zero(arr1))

print("Array 2:", arr2)
print("any of the elements in array 2 are zero:", none_zero(arr2))

Array 1: [1 2 3 4]
any of the elements in array 1 are zero: False
Array 2: [1 2 0 4]
any of the elements in array 2 are zero: True


#### Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [6]:


def compare_arrays(arr1, arr2, tol=1e-8):
    return np.allclose(arr1, arr2, atol=tol)

# Test the function
arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array([1.0, 2.0, 3.00000001])

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Are arrays 1 and 2 equal within tolerance?", compare_arrays(arr1, arr2))

print("Array 1:", arr1)
print("Array 3:", arr3)
print("Are arrays 1 and 3 equal within tolerance?", compare_arrays(arr1, arr3))


Array 1: [1. 2. 3.]
Array 2: [1. 2. 3.]
Are arrays 1 and 2 equal within tolerance? True
Array 1: [1. 2. 3.]
Array 3: [1.         2.         3.00000001]
Are arrays 1 and 3 equal within tolerance? True


#### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [7]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.full(10, 5)
result_array = np.concatenate([zeros_array, ones_array, fives_array])

print("Array of 10 zeros:", zeros_array)
print("Array of 10 ones:", ones_array)
print("Array of 10 fives:", fives_array)
print("Resulting array:", result_array)


Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]
Resulting array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


#### Write a NumPy program to create an array of the integers from 30 to70.


In [9]:
array_integers = np.arange(30, 71)

print("Array of integers from 30 to 70:\n", array_integers)


Array of integers from 30 to 70:
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#### Write a NumPy program to create a 3x3 identity matrix

In [10]:
identity_matrix = np.identity(3)

print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Write a NumPy program to generate a random number between 0 and 1

In [11]:
random_number = np.random.rand()

print("Random number between 0 and 1:", random_number)


Random number between 0 and 1: 0.39840722025543873


#### Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [12]:
random_numbers = np.random.randn(15)

print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)

Array of 15 random numbers from a standard normal distribution:
[-0.78654413 -0.49932165 -0.13039162 -2.51504262 -0.06276649 -0.90445882
 -0.2416997  -0.5668499  -0.05063573 -1.40137288  0.63373793  0.27359795
  0.32257825  0.03301795 -0.74051489]


#### Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [13]:
vector = np.arange(15, 56)
print("All values except the first and last:")
print(vector[1:-1])

All values except the first and last:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


####  a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 

In [14]:
vec = np.random.randint(0, 11, size = 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(vec)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[ 5 10  8  8  9]


### Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [15]:
matrix = np.zeros((10, 10))
matrix[0, :] = 1  
matrix[-1, :] = 1  
matrix[:, 0] = 1  
matrix[:, -1] = 1  

print("10x10 matrix with borders as 1 and inside as 0:")
print(matrix)

10x10 matrix with borders as 1 and inside as 0:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,3, 4, 5

In [16]:
matrix = np.zeros((5, 5))

np.fill_diagonal(matrix, [1, 2, 3, 4, 5])

print("5x5 matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5:")
print(matrix)

5x5 matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5:
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


#### Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [17]:

matrix = np.zeros((4, 4), dtype=int)

matrix[::2, 1::2] = 1  # Rows with even indices and columns with odd indices
matrix[1::2, ::2] = 1  # Rows with odd indices and columns with even indices

print("4x4 matrix with 0 and 1 staggered and zeros on the main diagonal:")
print(matrix)


4x4 matrix with 0 and 1 staggered and zeros on the main diagonal:
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


#### Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [18]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
np.savez_compressed('arrays.npz', array1 = array1, array2 = array2)
loaded_data = np.load('arrays.npz')
loaded_array1 = loaded_data['array1']
loaded_array2 = loaded_data['array2']
print("Loaded array 1:", loaded_array1)
print("Loaded array 2:", loaded_array2)

Loaded array 1: [1 2 3 4 5]
Loaded array 2: [ 6  7  8  9 10]


#### Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values Select

In [19]:
random_values = np.random.rand(40)

print("One-dimensional array of forty pseudo-randomly generated values:")
print(random_values)

One-dimensional array of forty pseudo-randomly generated values:
[0.19678602 0.03493709 0.52487349 0.85189903 0.18441688 0.34400556
 0.21902207 0.66313111 0.62297754 0.18739296 0.91763836 0.99354645
 0.84735998 0.43154593 0.66479518 0.50583228 0.83947706 0.12771714
 0.72632562 0.65651556 0.77084078 0.23132369 0.72407514 0.87611979
 0.4543784  0.41346142 0.1822633  0.01036833 0.90147783 0.74926448
 0.15467297 0.55430804 0.15222391 0.21722575 0.04294521 0.49057491
 0.36418343 0.29855364 0.97970815 0.79528819]


#### Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [20]:
def extract_numbers(arr, threshold):
    less_than_threshold = arr[arr < threshold]
    greater_than_threshold = arr[arr > threshold]
    return less_than_threshold, greater_than_threshold


array = np.array([1, 5, 10, 15, 20, 25, 30])
threshold = 15


less_than_threshold, greater_than_threshold = extract_numbers(array, threshold)

print("Numbers less than", threshold, ":", less_than_threshold)
print("Numbers greater than", threshold, ":", greater_than_threshold)

Numbers less than 15 : [ 1  5 10]
Numbers greater than 15 : [20 25 30]
