In [1]:
import numpy as np

Write a NumPy program to test whether none of the elements of a given array is zero.

In [2]:
a = np.array([1,2,3,4])
print("Is none of the elements = 0\n", np.all(a))

Is none of the elements = 0
 True


Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [3]:
a = np.array([0,1,2,3,4])
print("Is any of the elements = 0\n", not(np.all(a)))

Is any of the elements = 0
 True


Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given

In [4]:
a = np.array([0,1,2,3,4])
b = np.array([0,1,2,3,4.00001])
print("Equal Compsrison: ", np.equal(a, b))
print("Equal within a tolerance Compsrison: ", np.allclose(a, b))

Equal Compsrison:  [ True  True  True  True False]
Equal within a tolerance Compsrison:  True


Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [5]:
a = np.zeros(10)
print("10 zeros array = ", a)
b = np.ones(10)
print("10 ones array = ", b)
c = np.ones(10)*5
print("10 fives array = ", c)

10 zeros array =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10 ones array =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
10 fives array =  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of the integers from 30 to 70

In [6]:
a = np.arange(30,71)
print("Integers from 30 : 70 = \n", a)

Integers from 30 : 70 = 
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Write a NumPy program to create a 3x3 identity matrix 

In [7]:
a_id = np.identity(3)
print("3*3  identity matrix = \n", a_id)

3*3  identity matrix = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 Write a NumPy program to generate a random number between 0 and 1 

In [8]:
a_rand = np.random.sample(1)
print ("random number between 0 and 1 =",a_rand)

random number between 0 and 1 = [0.27169353]


Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution

In [9]:
a_rand = np.random.normal(0,1,15)
print ("15 random numbers from a standard normal distribution = \n",a_rand)

15 random numbers from a standard normal distribution = 
 [-0.84704169  1.88466507  0.99589589  0.54270113  0.63536415 -0.10721668
  0.59594065 -0.82376674  0.13571166  0.97332482  0.40868031  0.2787241
 -0.03841028  0.01229474 -0.37962962]


Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last

In [10]:
a = np.arange(15, 56)
print("The vector = \n", a)
print("The vector without first and last = \n", a[1:-1])

The vector = 
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
The vector without first and last = 
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [11]:
a = np.random.randint(0, 11, 5)
print("Vector of length 5 with arbitrary integers from 0 to 10 = \n", a)

Vector of length 5 with arbitrary integers from 0 to 10 = 
 [10  3  0  6  7]


Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0.

In [12]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print("The 10x10 matrix with ones in borders zeros inside = \n", a)

The 10x10 matrix with ones in borders zeros inside = 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5

In [13]:
a = np.diag([1, 2, 3, 4, 5])
print("The 5x5 matrix with [1, 2, 3, 4, 5] on the main diagonal = \n", a)

The 5x5 matrix with [1, 2, 3, 4, 5] on the main diagonal = 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.

In [14]:
a = np.zeros((4,4))
a[::2, 1::2] = 1
a[1::2,::2]=1
print("The 4x4 matrix Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the maindiagonal = \n", a)

The 4x4 matrix Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the maindiagonal = 
 [[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)
and load it.


In [15]:
a  = np.array([1,2,3,4,5])
b = np.array([11,12,13,14,15])
print("Original arrays:")
print(a)
print(b)
np.savez('temp_arr.npz', a_tmp=a, b_tmp=b)
print("Load arrays from the 'temp_arr.npz' file:")
with np.load('temp_arr.npz') as data:
    aa = data['a_tmp']
    bb = data['b_tmp']
    print(aa)
    print(bb)

Original arrays:
[1 2 3 4 5]
[11 12 13 14 15]
Load arrays from the 'temp_arr.npz' file:
[1 2 3 4 5]
[11 12 13 14 15]


Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.


In [16]:
np.random.seed(42)
a = np.random.rand(40)
print("One-dimensional array of 40 pseudo-randomly generated values = \n", a)

One-dimensional array of 40 pseudo-randomly generated values = 
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
 0.30461377 0.09767211 0.68423303 0.44015249]


Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.

In [17]:
a = np.arange(0,100)
n1 = 35
a_ext1 = a[(a > n1) ]
a_ext2 = a[(a < n1) ]
print ("Original array = \n", a)
print("Elements less than 35 = \n", a_ext1)
print("Elements greater than 35 = \n", a_ext2)

Original array = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Elements less than 35 = 
 [36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Elements greater than 35 = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]
