In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
type(my_list)

list

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
x= np.array(my_matrix)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
x.shape

(3, 3)

### Build-in methods 

#### arange
###### Return evenly spaced values within a given interval.

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones
#### Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
#### Return evenly spaced numbers over a specified interval.

In [15]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

### eye
#### Creates an identity matrix

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1]``.

In [17]:
np.random.rand(2)

array([0.8662996 , 0.99062397])

In [19]:
np.random.rand(5,5)

array([[0.93599211, 0.43436453, 0.1196757 , 0.78292137, 0.61029838],
       [0.33424834, 0.14956861, 0.23156649, 0.55310106, 0.17278977],
       [0.02579175, 0.52091553, 0.68406879, 0.41439046, 0.52212753],
       [0.93113288, 0.18299159, 0.03583835, 0.11602888, 0.75231559],
       [0.28540721, 0.84231369, 0.23190655, 0.42856088, 0.4184942 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(2)

array([-0.44907092,  0.2780581 ])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1, 100)

3

In [23]:
np.random.randint(1, 100, 10)

array([ 4, 65, 25, 92, 17, 74, 81, 44, 47,  4])

In [24]:
def fun(*args):

    z= sum(args)
    return z


In [25]:
fun(5, 6, 8)

19

## Array Attributes and Methods


In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

## Reshape

In [27]:
arr.reshape(5, 5).shape

(5, 5)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [32]:
ranarr

array([25, 29,  3, 29, 25, 23, 22, 12, 38, 21])

In [30]:
ranarr.max()

38

In [31]:
ranarr.argmax()

8

In [33]:
ranarr.min()

3

In [34]:
ranarr.argmin()

2

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [36]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
arr/arr

C:\Users\Dina\AppData\Local\Temp\ipykernel_17724\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [41]:
1/arr

C:\Users\Dina\AppData\Local\Temp\ipykernel_17724\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [42]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

In [43]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [44]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [45]:
np.max(arr)

9

In [46]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [47]:
np.log(arr)

C:\Users\Dina\AppData\Local\Temp\ipykernel_17724\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# NumPy Indexing and Selection

In [48]:
arr = np.arange(0, 11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
#Get a value at an index
arr[8]


8

In [51]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [52]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [53]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [56]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [57]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [58]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

In [59]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
#Indexing row
arr_2d[0:2]


array([[ 5, 10, 15],
       [20, 25, 30]])

In [61]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [62]:
# Getting individual element value
arr_2d[1,0]

20

In [63]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,0:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [64]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [65]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [68]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])